name: interval_time_picker
description: A variant of the default Flutter Time Picker in which you can pick intervals.
version: 2.0.0+6
homepage: https://github.com/Fleximex/interval_time_picker
repository: https://github.com/Fleximex/interval_time_picker

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
